-- ═══════════════════════════════════════════════════════════════════════════
-- EXAMFORGE — CD PYQ SEED v2 (Part 4 / 8)
-- MCQ Questions Q29–Q45 (Optimization & Runtime Environments) (clean)
-- ═══════════════════════════════════════════════════════════════════════════

-- Q29 — Basic Block execution (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='basic-blocks' LIMIT 1), 'gate-cse',false,NULL,'MCQ','easy',1, 'A Basic Block represents a sequence of continuous code instructions exhibiting:', 'Only one entry point and one exit point', 'Multiple entry points with loops', 'Variable loops inside the structure', 'Recursive call capacities', 'A', '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> A basic block guarantees straight-line code execution without internal branches or multiple entry/exit paths.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('optimization');

-- Q30 — Control Flow Graphs (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='basic-blocks' LIMIT 1), 'gate-cse',false,NULL,'MCQ','medium',2, 'Inside a Control Flow Graph (CFG), what do the nodes represent?', 'Individual variables', 'Basic blocks', 'Terminal tokens', 'Grammar productions', 'B', '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> CFG nodes encapsulate entire continuous Basic Blocks, with edges the conditional jumps between them.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('optimization');

-- Q31 — Peephole Optimization mechanics (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='peephole' LIMIT 1), 'gate-cse',false,NULL,'MCQ','easy',1, 'Peephole optimization typically operates passing a sliding window over which code state?', 'Source code', 'Intermediate representation', 'Target machine code', 'Lexical tokens', 'C', '<p><strong>✓ Answer: C.</strong></p><p><strong>Rationale:</strong> Peephole optimization is a localized pass occurring directly over generated target machine instructions.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('optimization');

-- Q32 — Common Subexpression Elimination (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='code-opt' LIMIT 1), 'gate-cse',false,NULL,'MCQ','medium',2, 'Which data structure is most appropriate to perform Local Common Subexpression Elimination?', 'Activation record stack', 'Directed Acyclic Graph (DAG)', 'State-Transition diagrams', 'Trie data sets', 'B', '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> By plotting logic onto a DAG, nodes with identical operations evaluate as single merged nodes, naturally eliminating common subexpressions.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('dag','optimization');

-- Q33 — Loop invariant code motion (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='code-opt' LIMIT 1), 'gate-cse',false,NULL,'MCQ','medium',2, 'Moving that evaluate irrespective of loop iterations into a pre-header block is classified as:', 'Loop unrolling', 'Strength reduction', 'Loop invariant code motion', 'Dead code elimination', 'C', '<p><strong>✓ Answer: C.</strong></p><p><strong>Rationale:</strong> Extracting logic that does not change across iterations prevents repetitive execution.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('optimization');

-- Q34 — Strength Reduction (hard)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='code-opt' LIMIT 1), 'gate-cse',false,NULL,'MCQ','hard',2, 'Replacing an expensive operation $X \times 2$ with the computationally cheaper instruction $X + X$ or $X \ll 1$ provides a classic example of:', 'Strength Reduction', 'Constant Folding', 'Algebraic Simplification', 'Code Hoisting', 'A', '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> Strength reduction specifically replaces an expensive hardware operator (multiplication) with a cheaper operator (addition or shifts).</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('optimization');

-- Q35 — Constant Folding Phase (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='code-opt' LIMIT 1), 'gate-cse',false,NULL,'MCQ','easy',1, 'When the compiler identifies $X = 3 \times 4$ and replaces it with $X = 12$ during compile time, it executes:', 'Strength Reduction', 'Constant Folding', 'Constant Propagation', 'Copy Propagation', 'B', '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> Constant folding evaluates deterministic literals at compile-time to save runtime .</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('optimization');

-- Q36 — Dead Code Definition (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='code-opt' LIMIT 1), 'gate-cse',false,NULL,'MCQ','easy',1, 'Instructions modifying variables that are subsequently never utilized downstream represent:', 'Loop variants', 'Live variables', 'Dead code', 'Aliased references', 'C', '<p><strong>✓ Answer: C.</strong></p><p><strong>Rationale:</strong> Dead code outputs results to targets that never pass into live analysis downstream streams, meaning they can be deleted .</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('optimization');

-- Q37 — Activation Record layout (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='runtime' LIMIT 1), 'gate-cse',false,NULL,'MCQ','medium',2, 'In a standard C compiler function states, the Activation Record contains:', 'Global variable locations only', 'Local variables, return address, and machine status', 'Static library dependencies', 'Heap allocations', 'B', '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> The activation record pushes runtime requirements including , local variables, dynamic links, and return addresses.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('runtime-env','activation');

-- Q38 — Static Allocation limits (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='runtime' LIMIT 1), 'gate-cse',false,NULL,'MCQ','medium',2, 'Compilers assigning memory exclusively via Static Allocation lose the capability to support:', 'Global variables', 'Recursive functions', 'Constant declarations', 'Array checks', 'B', '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> Static allocation uses fixed memory locations. Recursion requires dynamic scaling stacks matching successive activation scopes.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('runtime-env');

-- Q39 — Heap memory utilization (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='runtime' LIMIT 1), 'gate-cse',false,NULL,'MCQ','easy',1, 'Which mechanism manages objects bypassing LIFO stack constraints via functions like `malloc()`?', 'Register windows', 'Global static data zone', 'Heap memory allocation', 'Text execution block', 'C', '<p><strong>✓ Answer: C.</strong></p><p><strong>Rationale:</strong> The Heap allocates dynamic structures possessing lifetimes exceeding standard function stack block scopes.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('runtime-env');

-- Q40 — Parameter passing techniques (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='runtime' LIMIT 1), 'gate-cse',false,NULL,'MCQ','medium',2, 'Call-by-Reference parameter handling entails passing:', 'Value copies', 'Machine addresses linking to the original variable', 'Variable names directly', 'Duplicate scope blocks', 'B', '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> Call-by-reference shares the exact memory address (pointer), meaning changes inside the function propagate to the original variable.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('runtime-env');

-- Q41 — Call by Name semantics (hard)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='runtime' LIMIT 1), 'gate-cse',false,NULL,'MCQ','hard',2, 'Under Call-by-Name parameter parsing in languages like Algol, an argument expression is passed as:', 'Thunks delayed text substitutions', 'Constant numerical outputs', 'Memory pointers', 'String references', 'A', '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> Call-by-name textually replaces the parameter inside the function code, its mathematical dependencies (a "thunk") anew every time it is referenced.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('runtime-env');

-- Q42 — Data-flow equations components (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='data-flow' LIMIT 1), 'gate-cse',false,NULL,'MCQ','medium',2, 'Standard data flow analysis equations for basic blocks consist primarily of which sets?', 'GEN and KILL sets', 'First and Follow sets', 'Shift and Reduce sets', 'Lexical and Syntax sets', 'A', '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> The fundamental $OUT = GEN \cup (IN - KILL)$ equation manages local block impacts for data flow optimizations.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('optimization','data-flow');

-- Q43 — Display implementation (hard)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='runtime' LIMIT 1), 'gate-cse',false,NULL,'MCQ','hard',2, 'When supporting nested scoping inside block-structured languages, what data structure maps external references?', 'Graph nodes', 'Display arrays active pointers to outer lexical scopes', 'Register queues', 'Heap vectors', 'B', '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> A "Display" is an array of pointers allowing $O(1)$ access to variables in enclosing lexical boundaries.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('runtime-env');

-- Q44 — Next Use information (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='code-opt' LIMIT 1), 'gate-cse',false,NULL,'MCQ','medium',2, 'Which statement describes computing Next-Use inside Basic Blocks?', 'It calculates outputs scanning Top-to-Bottom', 'It evaluates scanning the block sequentially Bottom-to-Top', 'It requires multiple bidirectional passes', 'It relies on arbitrary execution jumps', 'B', '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> Basic block Next-Use properties compute traversing backward from the exit boundary upwards, variable liveness state changes accurately.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('liveness','optimization');

-- Q45 — Optimization levels (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='code-opt' LIMIT 1), 'gate-cse',false,NULL,'MCQ','easy',1, 'Which compiler optimization scope analyzes logic within a single procedure or function boundary?', 'Local optimization', 'Peephole optimization', 'Global (Intra-procedural) optimization', 'Inter-procedural optimization', 'C', '<p><strong>✓ Answer: C.</strong></p><p><strong>Rationale:</strong> Intra-procedural (Global) optimization analyzes across multiple basic blocks but remains contained within a single function. Local applies to single blocks. Inter-procedural applies across multiple functions.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('optimization');

-- Part 4 complete.
