-- ═══════════════════════════════════════════════════════════════════════════
-- EXAMFORGE — CD PYQ SEED v2 (Part 3 / 8)
-- MCQ Questions Q15–Q28 (SDT, ICG, Attributes)
-- ═══════════════════════════════════════════════════════════════════════════

-- Q15 — Synthesized attributes (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='attributes' LIMIT 1), 'gate-cse',false,NULL,'MCQ','easy',1, 'In Syntax-Directed Translation, what evaluates a synthesized attribute computing at a parse tree node $N$?', 'The attributes from the parent node', 'The attributes from its direct child nodes', 'The attributes from sibling nodes', 'Attributes from the root', 'B', '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> Synthesized attributes calculate values bottom-up using data from child components.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('sdt');

-- Q16 — S-Attributed definitions (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='att-types' LIMIT 1), 'gate-cse',false,NULL,'MCQ','medium',2, 'An S-Attributed Grammar Definition relies exclusively on which attribute type?', 'Inherited attributes', 'Synthesized attributes', 'Both Inherited and Synthesized', 'Lookahead tokens', 'B', '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> S-Attributed grammars compute Synthesized values flowing bottom-up.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('sdt');

-- Q17 — L-Attributed conditions (hard)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='att-types' LIMIT 1), 'gate-cse',false,NULL,'MCQ','hard',2, 'For rule $A \rightarrow X_1 X_2 X_3$ in an L-Attributed environment, the inherited attributes of $X_2$ depend on:', 'Attributes of $X_1, X_2$, and $X_3$', 'Attributes of parent $A$ and left sibling $X_1$', 'Attributes of $X_3$ and $A$', 'Synthesized attributes of $X_2$', 'B', '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> L-Attributed grammars compute Top-Down and Left-to-Right. The attributes of $X_2$ rely on parent $A$ and left sibling $X_1$.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('sdt');

-- Q18 — Three-Address Code constructs (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='tac' LIMIT 1), 'gate-cse',false,NULL,'MCQ','easy',1, 'The fundamental property of Three-Address Code (TAC) is that each instruction specifies:', 'Exactly infinite operands', 'At most three addresses (two operands, one result)', 'Exactly two addresses', 'Only memory blocks without operations', 'B', '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> TAC processes instructions using a maximum of 3 addresses per statement.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('icg');

-- Q19 — Quadruples implementation (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='tac' LIMIT 1), 'gate-cse',false,NULL,'MCQ','medium',2, 'When TAC using quadruples, which fields are required?', 'Operator, Argument 1, Argument 2, and Result', 'Argument 1, Argument 2, Result', 'Memory addresses and values', 'Output variable and computation', 'A', '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> A Quadruple requires 4 exact fields: Operator, Arg1, Arg2, and Result.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('icg');

-- Q20 — Abstract Syntax Tree compression (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='ast' LIMIT 1), 'gate-cse',false,NULL,'MCQ','medium',2, 'How does an Abstract Syntax Tree (AST) differ from a Parse Tree?', 'ASTs eliminate redundant structural tokens like parentheses', 'ASTs include all terminals', 'ASTs represent code at assembly level', 'ASTs only track comments', 'A', '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> ASTs compress Parse Trees by dropping punctuation and structural artifacts.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('parsing');

-- Q21 — Directed Acyclic Graph efficiency (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='dag-topic' LIMIT 1), 'gate-cse',false,NULL,'MCQ','easy',1, 'What is the primary optimization benefit of a Directed Acyclic Graph (DAG) over an AST?', 'It identifies and shares common subexpressions', 'It removes all operators', 'It compiles faster to binary', 'It reduces global variables', 'A', '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> DAG evaluations determine common subexpressions and merge identical nodes.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('dag','optimization');

-- Q22 — Bootstrapping Compiler Process (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='lexical-analysis' LIMIT 1), (SELECT id FROM topics WHERE slug='token-identification' LIMIT 1), 'gate-cse',false,NULL,'MCQ','easy',1, 'The compiler term "bootstrapping" refers to:', 'Writing a compiler in the same language it compiles', 'Optimizing loops', 'Loading the OS', 'Linking static libraries', 'A', '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> Bootstrapping is a self-compiling compiler.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('lexical-analysis');

-- Q23 — SDT Implementation structures (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='attributes' LIMIT 1), 'gate-cse',false,NULL,'MCQ','medium',2, 'In which parsing method can S-Attributed definitions be most easily implemented?', 'Top-Down LL(1)', 'Bottom-Up LR Parsing', 'Recursive Descent', 'Operator Precedence', 'B', '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> S-Attributed definitions evaluate bottom-up, matching LR parser reduction events.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('sdt');

-- Q24 — Syntax Tree vs Parse Tree limits (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='ast' LIMIT 1), 'gate-cse',false,NULL,'MCQ','easy',1, 'Which nodes typically form the interior of an AST?', 'Operators', 'Operands', 'Punctuation marks', 'Variables exactly as in parse trees', 'A', '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> AST interior nodes act as operators, leaf nodes act as operands.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('ast');

-- Q25 — Data flow analysis foundations (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='data-flow' LIMIT 1), 'gate-cse',false,NULL,'MCQ','medium',2, 'Live Variable Analysis is critical primarily for:', 'Register allocation algorithms', 'Loop unrolling optimizations', 'Parse tree reductions', 'Lexical buffer allocations', 'A', '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> Register allocation depends on liveness analysis to know when a variable is no longer needed.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('liveness','optimization');

-- Q26 — SSA form (hard)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='tac' LIMIT 1), 'gate-cse',false,NULL,'MCQ','hard',2, 'In Static Single Assignment (SSA) form, what resolves intersecting control flow paths assigning to the same variable?', 'Alpha functions', 'Phi ($\Phi$) functions', 'Gamma assignments', 'Delta assignments', 'B', '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> $\Phi$ functions merge assignments arising from multiple incoming control paths.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('icg');

-- Q27 — Triples array layout (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='tac' LIMIT 1), 'gate-cse',false,NULL,'MCQ','easy',1, 'How do Triples differ from Quadruples in TAC implementations?', 'They use pointers to statement indices instead of explicit result variables', 'They lack an operator field', 'They require four memory addresses per cell', 'They only support Boolean logic', 'A', '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> Triples avoid creating dummy temporary variables, referencing the index of the statement directly.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('icg');

-- Q28 — Indirect Triples benefits (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_option,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='tac' LIMIT 1), 'gate-cse',false,NULL,'MCQ','medium',2, 'Why are Indirect Triples preferred over Standard Triples during code optimization?', 'They allow instruction reordering without updating pointers', 'They use less memory per instruction', 'They skip syntax validations', 'They encode floating-point limits differently', 'A', '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> Standard Triples tie pointers to explicit array indices. Indirect Triples use an array of pointers, permitting easy line swaps.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('icg');

-- Part 3 complete.
