-- ═══════════════════════════════════════════════════════════════════════════
-- EXAMFORGE — OS PYQ SEED v2 (Part 6 / 8)
-- MSQ Questions Q56–Q65 (OS Multi-Select Properties)
-- ═══════════════════════════════════════════════════════════════════════════

-- Q56 — MSQ: Preemptive Schedulers (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='os'), (SELECT id FROM chapters WHERE slug='process-management' LIMIT 1), (SELECT id FROM topics WHERE slug='scheduling' LIMIT 1), 'gate-cse',false,NULL,'MSQ','easy',1, 'Which of the following process scheduling algorithms support preemption? (Select all that apply)', 'Shortest Remaining Time First (SRTF)', 'Round Robin', 'First-Come-First-Serve (FCFS)', 'Shortest Job First (Classic SJF)', ARRAY['A','B'], '<p><strong>✓ Answers: A, B.</strong></p><p><strong>Rationale:</strong> SRTF and Round Robin preempt running by design based on arrival of shorter jobs or timer expirations. FCFS and base SJF are non-preemptive.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('scheduling');

-- Q57 — MSQ: Deadlock prevention tactics (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='os'), (SELECT id FROM chapters WHERE slug='concurrency' LIMIT 1), (SELECT id FROM topics WHERE slug='deadlock-concept' LIMIT 1), 'gate-cse',false,NULL,'MSQ','medium',2, 'To prevent deadlocks, systems can deny standard Coffman conditions. Which designs actively break "Hold and Wait"? (Select all that apply)', 'A process must request and be allocated all necessary resources before beginning execution', 'A process requesting new resources must first release all currently held resources', 'Linearly ordering all resources numerically', 'Killing processes holding locks too long', ARRAY['A','B'], '<p><strong>✓ Answers: A, B.</strong></p><p><strong>Rationale:</strong> Requesting all at once, or dropping everything before asking anew ensures a process never holds one item while waiting for another.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('deadlock');

-- Q58 — MSQ: Virtual Memory benefits (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='os'), (SELECT id FROM chapters WHERE slug='memory-management' LIMIT 1), (SELECT id FROM topics WHERE slug='virtual' LIMIT 1), 'gate-cse',false,NULL,'MSQ','medium',2, 'Implementing virtual memory by demand paging yields which practical advantages? (Select all that apply)', 'The degree of multiprogramming can be increased', 'Total physical memory capacity logical program sizes', 'Logical address spaces can significantly exceed physical RAM confines', 'Page sharing allows identical library code to load exactly once', ARRAY['A','C','D'], '<p><strong>✓ Answers: A, C, D.</strong></p><p><strong>Rationale:</strong> Virtual memory breaks standard RAM constraints allowing massive programs, code sharing, and a higher count of active running processes.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('paging');

-- Q59 — MSQ: Thread Sharing (hard)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='os'), (SELECT id FROM chapters WHERE slug='process-management' LIMIT 1), (SELECT id FROM topics WHERE slug='threads' LIMIT 1), 'gate-cse',false,NULL,'MSQ','hard',2, 'Peer threads operating within the exact same parent process intrinsically share which underlying components? (Select all that apply)', 'The Data Section', 'The Code (Text) Section', 'Open OS File Descriptors', 'The local Call Stack', ARRAY['A','B','C'], '<p><strong>✓ Answers: A, B, C.</strong></p><p><strong>Rationale:</strong> Threads share global states: code, global data, and OS handles. They maintain private stacks and private registers their unique execution .</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('threads');

-- Q60 — MSQ: Thrashing causes (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='os'), (SELECT id FROM chapters WHERE slug='memory-management' LIMIT 1), (SELECT id FROM topics WHERE slug='virtual' LIMIT 1), 'gate-cse',false,NULL,'MSQ','medium',2, 'Which trigger or worsen OS Thrashing? (Select all that apply)', 'The degree of multiprogramming exceeds active memory capacity ', 'Operating processes mapped with insufficient frame allocations', 'A low page-fault rate', 'Global page replacement algorithms stealing priority frames', ARRAY['A','B','D'], '<p><strong>✓ Answers: A, B, D.</strong></p><p><strong>Rationale:</strong> Running too many programs, providing too few frames per process, and using aggressive global replacement policies cause chronic faults driving thrashing.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('paging');

-- Q61 — MSQ: Semaphores properties (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='os'), (SELECT id FROM chapters WHERE slug='concurrency' LIMIT 1), (SELECT id FROM topics WHERE slug='sync-tools' LIMIT 1), 'gate-cse',false,NULL,'MSQ','easy',1, 'Which characteristics validly define standard OS Counting Semaphores? (Select all that apply)', 'They integrate atomic P and V commands', 'They possess binary 0 or 1 boundaries', 'They regulate concurrent limit access without tying to lock owners', 'They function bypassing context switch penalties', ARRAY['A','C'], '<p><strong>✓ Answers: A, C.</strong></p><p><strong>Rationale:</strong> Counting semaphores differ from binary semaphores (mutexes); they scale mathematically protecting of multiple identical resources without specific ownership.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('semaphores');

-- Q62 — MSQ: Kernel thread vs User Thread (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='os'), (SELECT id FROM chapters WHERE slug='process-management' LIMIT 1), (SELECT id FROM topics WHERE slug='threads' LIMIT 1), 'gate-cse',false,NULL,'MSQ','medium',2, 'Kernel-level threads maintain which technical advantages against User-level threads? (Select all that apply)', 'If one thread invokes a blocking system call, sibling threads continue freely', 'The OS routes distinct threads simultaneously across varying multicore CPUs', 'Creation and destruction metrics operate considerably faster', 'They do not require kernel mode traps invoking scheduling logic', ARRAY['A','B'], '<p><strong>✓ Answers: A, B.</strong></p><p><strong>Rationale:</strong> User threads are invisible to the OS (causing total process blocks). Kernel threads natively allow true multiprocessor and isolate blocking .</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('threads');

-- Q63 — MSQ: Disk structure algorithms (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='os'), (SELECT id FROM chapters WHERE slug='storage-io' LIMIT 1), (SELECT id FROM topics WHERE slug='disk' LIMIT 1), 'gate-cse',false,NULL,'MSQ','medium',2, 'Which disk scheduling successfully solve starvation (i.e., every request is mathematically guaranteed servicing quickly)? (Select all that apply)', 'FCFS', 'C-SCAN', 'SSTF', 'Shortest Job First', ARRAY['A','B'], '<p><strong>✓ Answers: A, B.</strong></p><p><strong>Rationale:</strong> FCFS processes in sequence. C-SCAN sweeps perfectly guaranteeing no request waits forever. Both SSTF and SJF suffer crippling starvation targets.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('disk');

-- Q64 — MSQ: Linked List File allocation (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='os'), (SELECT id FROM chapters WHERE slug='storage-io' LIMIT 1), (SELECT id FROM topics WHERE slug='file-alloc' LIMIT 1), 'gate-cse',false,NULL,'MSQ','easy',1, 'Linked Allocation methodologies file provide which benefits over Contiguous techniques? (Select all that apply)', 'zero External Fragmentation', 'Immediate $O(1)$ random accessibility calculating vectors', 'Dynamic file growth scaling endlessly', 'No need pre-declaring total sizes', ARRAY['A','C','D'], '<p><strong>✓ Answers: A, C, D.</strong></p><p><strong>Rationale:</strong> Linked connect arbitrarily scattered blocks ending external fragmentation. However, accessing the $N$th block demands linear scanning, failing $O(1)$ targets.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('disk');

-- Q65 — MSQ: Paging (hard)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='os'), (SELECT id FROM chapters WHERE slug='memory-management' LIMIT 1), (SELECT id FROM topics WHERE slug='paging' LIMIT 1), 'gate-cse',false,NULL,'MSQ','hard',2, 'Multi-level paging frameworks replace massive scalar Page Tables memory aiming to:', 'Prevent holding unused empty occupying memory', 'Drop Translation Lookaside Buffers ', 'Establish logic allowing page tables themselves bounding to map onto disk swaps', 'Speed up absolute cache miss hardware fetches significantly', ARRAY['A','C'], '<p><strong>✓ Answers: A, C.</strong></p><p><strong>Rationale:</strong> Multi-level logic drops unused arrays (saving giant blocks of space) and allows outer page tables loading into RAM lazily. It does NOT speed up ; adding levels makes misses slower.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('paging');

-- Part 6 complete.
