-- ═══════════════════════════════════════════════════════════════════════════
-- EXAMFORGE — OS PYQ SEED v2  (Part 8 / 8)
-- Flashcards Part 2: Memory & Storage (11 Cards) + COMMIT
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO flashcards (subject_id,chapter_id,topic_id,front,back,tags) VALUES
-- Card 12
(
  (SELECT id FROM subjects WHERE slug='os'),
  (SELECT id FROM chapters WHERE slug='memory-management' LIMIT 1),
  (SELECT id FROM topics WHERE slug='paging' LIMIT 1),
  'What is the difference between Logical and Physical Addresses?',
  '<p>A Logical Address is generated by the CPU executing a program. A Physical Address represents the actual location inside the RAM hardware. The MMU handles mapping the former into the latter.</p>',
  ARRAY['paging']
),
-- Card 13
(
  (SELECT id FROM subjects WHERE slug='os'),
  (SELECT id FROM chapters WHERE slug='memory-management' LIMIT 1),
  (SELECT id FROM topics WHERE slug='paging' LIMIT 1),
  'Differentiate Internal vs External Fragmentation.',
  '<p><strong>Internal:</strong> Wasted space inside an allocated block (e.g. fixed paging).<br><strong>External:</strong> Ample free memory exists across the system, but it is shattered into non-contiguous gaps prohibiting allocations.</p>',
  ARRAY['paging']
),
-- Card 14
(
  (SELECT id FROM subjects WHERE slug='os'),
  (SELECT id FROM chapters WHERE slug='memory-management' LIMIT 1),
  (SELECT id FROM topics WHERE slug='segmentation' LIMIT 1),
  'How does Segmentation differ from Paging?',
  '<p>Paging splits memory into fixed-size mathematical blocks, causing internal fragmentation. Segmentation partitions memory based on logical user-defined blocks (like functions or structures), causing external fragmentation.</p>',
  ARRAY['paging']
),
-- Card 15
(
  (SELECT id FROM subjects WHERE slug='os'),
  (SELECT id FROM chapters WHERE slug='memory-management' LIMIT 1),
  (SELECT id FROM topics WHERE slug='tlb' LIMIT 1),
  'What is the role of the TLB?',
  '<p>The Translation Lookaside Buffer (TLB) acts as a high-speed associative hardware cache storing recent page-table operations. A TLB hit avoids an expensive secondary trip to main memory for address translation.</p>',
  ARRAY['tlb']
),
-- Card 16
(
  (SELECT id FROM subjects WHERE slug='os'),
  (SELECT id FROM chapters WHERE slug='memory-management' LIMIT 1),
  (SELECT id FROM topics WHERE slug='virtual' LIMIT 1),
  'Define Thrashing.',
  '<p>Thrashing happens when active working sets surpass physical RAM frames. The OS stalls executing user code, spending virtually all CPU cycles continuously swapping pages in and out of the disk.</p>',
  ARRAY['paging']
),
-- Card 17
(
  (SELECT id FROM subjects WHERE slug='os'),
  (SELECT id FROM chapters WHERE slug='memory-management' LIMIT 1),
  (SELECT id FROM topics WHERE slug='page-replacement' LIMIT 1),
  'What is Belady''s Anomaly?',
  '<p>A counter-intuitive phenomenon found in FIFO page algorithms where increasing the number of available physical memory frames mathematically results in an increased number of page faults.</p>',
  ARRAY['paging']
),
-- Card 18
(
  (SELECT id FROM subjects WHERE slug='os'),
  (SELECT id FROM chapters WHERE slug='storage-io' LIMIT 1),
  (SELECT id FROM topics WHERE slug='disk' LIMIT 1),
  'What are the three components comprising Disk Access Time?',
  '<ol><li><strong>Seek Time:</strong> Moving the mechanical head to the target track.</li><li><strong>Rotational Latency:</strong> Waiting for the required sector to spin under the head.</li><li><strong>Transfer Time:</strong> Electronically copying the bytes.</li></ol>',
  ARRAY['disk']
),
-- Card 19
(
  (SELECT id FROM subjects WHERE slug='os'),
  (SELECT id FROM chapters WHERE slug='storage-io' LIMIT 1),
  (SELECT id FROM topics WHERE slug='disk' LIMIT 1),
  'Why does SSTF scheduling suffer from Starvation?',
  '<p>Shortest Seek Time First continuously jumps to the closest pending request. If a constant stream of local requests arrives, requests stationed far off at disk edges will be starved infinitely.</p>',
  ARRAY['disk']
),
-- Card 20
(
  (SELECT id FROM subjects WHERE slug='os'),
  (SELECT id FROM chapters WHERE slug='storage-io' LIMIT 1),
  (SELECT id FROM topics WHERE slug='disk' LIMIT 1),
  'What is the difference between SCAN and C-SCAN disk scheduling?',
  '<p>SCAN (Elevator) travels from $0 \rightarrow End$ servicing requests, then reverses direction servicing backward. C-SCAN strictly jumps back to 0 without servicing anything on the return voyage, preventing bias towards central tracks.</p>',
  ARRAY['disk']
),
-- Card 21
(
  (SELECT id FROM subjects WHERE slug='os'),
  (SELECT id FROM chapters WHERE slug='storage-io' LIMIT 1),
  (SELECT id FROM topics WHERE slug='file-alloc' LIMIT 1),
  'What is the fatal drawback of Contiguous File Allocation?',
  '<p>While offering phenomenal sequential access speeds, contiguous arrays fall prey immediately to External Fragmentation, demanding slow disk compaction runs over time as memory deletes produce gaps.</p>',
  ARRAY['disk']
),
-- Card 22
(
  (SELECT id FROM subjects WHERE slug='os'),
  (SELECT id FROM chapters WHERE slug='storage-io' LIMIT 1),
  (SELECT id FROM topics WHERE slug='unix-inode' LIMIT 1),
  'How do UNIX inodes support massive data structures?',
  '<p>Inodes balance accessing tiny and huge files by keeping 12 direct pointers initially, relying on cascading single, double, and triple-indirect structural blocks to multiply available logical bounds for massive payloads.</p>',
  ARRAY['disk']
);

COMMIT;

-- ─── POST-SEED VERIFICATION QUERIES ──────────────────────────────────────
-- Run these after executing os-seed.sql to verify correctness:
--
-- SELECT COUNT(*) FROM topics
--   WHERE chapter_id IN (SELECT id FROM chapters
--     WHERE subject_id = (SELECT id FROM subjects WHERE slug='os'));
-- Expected: 15
--
-- SELECT COUNT(*) FROM questions
--   WHERE subject_id = (SELECT id FROM subjects WHERE slug='os');
-- Expected: 65
--
-- SELECT COUNT(*) FROM flashcards
--   WHERE subject_id = (SELECT id FROM subjects WHERE slug='os');
-- Expected: 22
--
-- SELECT type, COUNT(*) FROM questions
--   WHERE subject_id = (SELECT id FROM subjects WHERE slug='os')
--   GROUP BY type;
-- Expected: MCQ: 45, NAT: 10, MSQ: 10

-- ─── STATS COMMENT BLOCK ─────────────────────────────────────────────────
-- STATS:
-- Subject slug: os
-- Schema version: v2 (normalized tags, NUMERIC(10,2) NAT, topic enforcement)
-- Chapters:     4 
-- Topics:       15
-- Questions:    65 total
--   MCQ:        45 (Q1–Q45)
--   NAT:        10 (Q46–Q55)
--   MSQ:        10 (Q56–Q65)
-- Flashcards:   22 concise OS structural cards
-- ═══════════════════════════════════════════════════════════════════════════
-- END OF os-seed.sql
-- ═══════════════════════════════════════════════════════════════════════════
