-- ═══════════════════════════════════════════════════════════════════════════
-- EXAMFORGE — CD PYQ SEED v2 (Part 6 / 8)
-- MSQ Questions Q56–Q65 (Multi-Select Compiler Traits)
-- ═══════════════════════════════════════════════════════════════════════════

-- Q56 — MSQ: Lexer tasks (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='lexical-analysis' LIMIT 1), (SELECT id FROM topics WHERE slug='token-identification' LIMIT 1), 'gate-cse',false,NULL,'MSQ','easy',1, 'Which operations are performed during the Lexical Analysis phase? (Select all that apply)', 'Matching regular expressions to generate tokens', 'Stripping whitespaces and removing comments', 'Verifying brackets and parenthesis balancing', 'Detecting identifier string sequences', ARRAY['A','B','D'], '<p><strong>✓ Answers: A, B, D.</strong></p><p><strong>Rationale:</strong> Lexical analysis utilizes DFA limits to trim spaces, remove comments, and recognize identifiers/constants. parenthesis requires stack logic (Syntax Analysis phase).</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('lexical-analysis');

-- Q57 — MSQ: LR Parser strengths (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='syntax-analysis' LIMIT 1), (SELECT id FROM topics WHERE slug='lr0-slr1' LIMIT 1), 'gate-cse',false,NULL,'MSQ','medium',2, 'Why are Bottom-Up LR Parsers more powerful than Top-Down LL Parsers? (Select all that apply)', 'LR parses shift tokens delaying decision until the rule handle is complete', 'LR supports and left-recursive grammars', 'LR constructs require matching predictive table loops traversing top-down', 'LR covers a mathematically larger subset of deterministic Context-Free properties', ARRAY['A','B','D'], '<p><strong>✓ Answers: A, B, D.</strong></p><p><strong>Rationale:</strong> LR handles left-recursion perfectly and parses all DCFL bounds. Top-Down logic requires predicting immediately upon reading the first token, restricting capability.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('lr-parsing');

-- Q58 — MSQ: S-Attributed characteristics (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='att-types' LIMIT 1), 'gate-cse',false,NULL,'MSQ','medium',2, 'Which statements accurately categorize S-Attributed SDT structures? (Select all that apply)', 'They exclusively evaluate synthesized ', 'They map inside bottom-up LR evaluations ', 'They assign data calculating child conditions passing to parent edges', 'They rely parsing logic top-down limits exclusively', ARRAY['A','B','C'], '<p><strong>✓ Answers: A, B, C.</strong></p><p><strong>Rationale:</strong> S-Attributed data synthesizes upwards (child to parent), which integrates perfectly matching the Right-Hand-Side handle reductions found inside LR passing tools.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('sdt');

-- Q59 — MSQ: Optimization loop constraints (hard)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='code-opt' LIMIT 1), 'gate-cse',false,NULL,'MSQ','hard',2, 'Code Optimization logic classifies several mechanisms targeting repeating Loop segments. Select valid Loop optimizations.', 'Strength Reduction inside calculations', 'Loop Invariant Code Motion', 'Induction Variable elimination', 'Peephole Optimization limits target outputs', ARRAY['A','B','C'], '<p><strong>✓ Answers: A, B, C.</strong></p><p><strong>Rationale:</strong> Strength reduction, induction elimination, and code motion specifically optimize looping performance metrics. Peephole targets localized machine instructions, independent of global loop architectures.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('optimization');

-- Q60 — MSQ: TAC equivalents (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='tac' LIMIT 1), 'gate-cse',false,NULL,'MSQ','medium',2, 'Intermediate Code operates across diverse structures data formats. Which apply as valid Intermediate Code abstractions? (Select all that apply)', 'Three-Address Code (TAC)', 'Static Single Assignment (SSA)', 'Post-fix / Polish Notation', 'Context-Sensitive syntax trees', ARRAY['A','B','C'], '<p><strong>✓ Answers: A, B, C.</strong></p><p><strong>Rationale:</strong> Compilers construct logic utilizing TAC, SSA , and Post-Fix logic strings as mathematical intermediate language mappings bridging frontend and backend code blocks.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('icg');

-- Q61 — MSQ: Shift-Reduce detection constraints (hard)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='syntax-analysis' LIMIT 1), (SELECT id FROM topics WHERE slug='shift-reduce' LIMIT 1), 'gate-cse',false,NULL,'MSQ','hard',2, 'In typical Bottom-Up parsing execution calculating bounds limits, Shift-Reduce conflict matrices occur which conditions? (Select all that apply)', 'The parser must select between pushing a valid terminal and applying a completed right-hand production', 'An ambiguous grammar like "Dangling Else" logic presents competing execution paths', 'Lookahead calculations calculate identical intersection targets overlapping actions', 'The item state matches exclusively complete reduction nodes', ARRAY['A','B','C'], '<p><strong>✓ Answers: A, B, C.</strong></p><p><strong>Rationale:</strong> Ambiguity naturally generates shift-reduce conflicts. Overlapping lookaheads in SLR or LALR tables cause the machine to debate shifting a token versus concluding a derivation (reducing).</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('lr-parsing');

-- Q62 — MSQ: Register Allocation strategies (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='code-opt' LIMIT 1), 'gate-cse',false,NULL,'MSQ','medium',2, 'Register Allocation manages hardware limits code limits predicting outputs structures. Algorithms employ which techniques? (Select all that apply)', 'Graph Coloring matching interference bounds', 'Liveness analysis active variable chains', 'Heuristic graph spilling reducing conflicts', 'Syntax matching lexical buffer sizes', ARRAY['A','B','C'], '<p><strong>✓ Answers: A, B, C.</strong></p><p><strong>Rationale:</strong> Interference graphs define live variable collisions, graph coloring paints variables calculating optimal memory spots, and spilling pushes excess data memory constraints to the stack array.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('optimization');

-- Q63 — MSQ: Symbol Table contents (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='lexical-analysis' LIMIT 1), (SELECT id FROM topics WHERE slug='token-identification' LIMIT 1), 'gate-cse',false,NULL,'MSQ','easy',1, 'A standard compiler Symbol Table maintains critical information bounds. Which data points are stored? (Select all that apply)', 'Variable name strings and lexical properties', 'Scope active lifetimes', 'Data type logic (int, float) byte bounds', 'Dynamic execution time logs managing bounds', ARRAY['A','B','C'], '<p><strong>✓ Answers: A, B, C.</strong></p><p><strong>Rationale:</strong> Symbol tables manage compile-time boundaries variables, , scope rules, and typing values. Execution happens locally run-time environments.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('lexical-analysis');

-- Q64 — MSQ: Peephole limits logic constraints (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='peephole' LIMIT 1), 'gate-cse',false,NULL,'MSQ','medium',2, 'Peephole verify structural conditions processing targeting limits paths. Select applicable properties.', 'Redundant Load/Store elimination memory ', 'Jumps bounds Jump commands (Branch chaining)', 'Dead branch removal passing fixed logic constraints', 'Global recursion reduction predicting loop invariants', ARRAY['A','B','C'], '<p><strong>✓ Answers: A, B, C.</strong></p><p><strong>Rationale:</strong> Peephole optimizations look inside short sequences detecting jumps-to-jumps, deleting unneeded local memory loads traversing logic blocks, and stripping dead constants. Recursion analysis operates global variables.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('optimization');

-- Q65 — MSQ: Top-Down parser failures (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,option_a,option_b,option_c,option_d,correct_options,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='syntax-analysis' LIMIT 1), (SELECT id FROM topics WHERE slug='ll1-parsing' LIMIT 1), 'gate-cse',false,NULL,'MSQ','easy',1, 'Predictive Top-Down parsers LL(1) logic checks logic limitations fail completing grammar checks containing:', 'Left-recursive parameter properties', 'Non-deterministic prefix bounding overlap rules', 'Syntax components exact single derivations loops', 'Ambiguous bounds equivalent logic rules', ARRAY['A','B','D'], '<p><strong>✓ Answers: A, B, D.</strong></p><p><strong>Rationale:</strong> Top-down predictive models require clean, deterministic, left-factored logic to select one derivation table row. Therefore Left-recursion, identical overlapping prefixes, and ambiguity mathematically block functionality.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('parsing');

-- Part 6 complete.
