-- ═══════════════════════════════════════════════════════════════════════════
-- EXAMFORGE — TOC PYQ SEED v2  (Part 3 / 8)
-- MCQ Questions Q15–Q28 (Context-Free Grammars & PDA)
-- ═══════════════════════════════════════════════════════════════════════════

-- Q15 — CFG Ambiguity (easy)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,option_a,option_b,option_c,option_d,correct_option,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='toc'),
  (SELECT id FROM chapters WHERE slug='context-free-languages' LIMIT 1),
  (SELECT id FROM topics WHERE slug='cfg-ambiguity' LIMIT 1),
  'gate-cse',false,NULL,'MCQ','easy',1,
  'A Context-Free Grammar (CFG) is classified as ambiguous if:',
  'It cannot be reduced to Chomsky Normal Form',
  'It has at least two distinct left-most derivations for the same string',
  'It generates the empty string',
  'No Pushdown Automaton can accept it',
  'B',
  '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> Ambiguity occurs when a single string can be generated by multiple distinct parse trees (e.g., more than one leftmost derivation or rightmost derivation).</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('cfg');

-- Q16 — Chomsky Normal Form (medium)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,option_a,option_b,option_c,option_d,correct_option,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='toc'),
  (SELECT id FROM chapters WHERE slug='context-free-languages' LIMIT 1),
  (SELECT id FROM topics WHERE slug='chomsky-normal' LIMIT 1),
  'gate-cse',false,NULL,'MCQ','medium',2,
  'In generating a string of exactly $n$ terminals ($n > 0$), what is the number of derivation steps required by a CFG in Chomsky Normal Form (CNF)?',
  '$n$',
  '$n-1$',
  '$2n-1$',
  '$2^n$',
  'C',
  '<p><strong>✓ Answer: C — $2n-1$.</strong></p><p><strong>Step-by-step:</strong><br>CNF restricts productions to $A \rightarrow BC$ or $A \rightarrow a$.<br>Generating $n$ separate terminals requires $n-1$ splitting steps to produce $n$ variables. Converting the $n$ variables takes $n$ steps. Total steps = $(n-1) + n = 2n-1$.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('cfg');

-- Q17 — Non-Context Free Language (hard)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,option_a,option_b,option_c,option_d,correct_option,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='toc'),
  (SELECT id FROM chapters WHERE slug='context-free-languages' LIMIT 1),
  (SELECT id FROM topics WHERE slug='cfl-closure' LIMIT 1),
  'gate-cse',false,NULL,'MCQ','hard',2,
  'Which language is NOT Context-Free?',
  '$L = \{a^n b^n c^n \mid n \ge 1\}$',
  '$L = \{a^n b^n \mid n \ge 1\}$',
  '$L = \{w w^R \mid w \in (a,b)^*\}$',
  '$L = \{a^n b^m \mid n \neq m\}$',
  'A',
  '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> The language $a^n b^n c^n$ requires maintaining equality across three constraints. A standard Pushdown Automaton with a single stack can only balance two variables, making this language Context-Sensitive.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('cfl-closure','hierarchy');

-- Q18 — DCFL vs CFL (medium)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,option_a,option_b,option_c,option_d,correct_option,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='toc'),
  (SELECT id FROM chapters WHERE slug='context-free-languages' LIMIT 1),
  (SELECT id FROM topics WHERE slug='pda-basics' LIMIT 1),
  'gate-cse',false,NULL,'MCQ','medium',2,
  'Which operational property differentiates Deterministic Context-Free Languages (DCFL) from Context-Free Languages (CFL)?',
  'DCFL representations are closed under complement operation',
  'DCFL representations are regular',
  'DCFL representations allow multiple stack operations per transition',
  'DCFLs can be recognized by finite automata',
  'A',
  '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> Unlike traditional CFLs (which fail complement closure), Deterministic CFLs are closed under the complement operator.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('cfl-closure','pda');

-- Q19 — PDA Null State Acceptance (easy)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,option_a,option_b,option_c,option_d,correct_option,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='toc'),
  (SELECT id FROM chapters WHERE slug='context-free-languages' LIMIT 1),
  (SELECT id FROM topics WHERE slug='pda-basics' LIMIT 1),
  'gate-cse',false,NULL,'MCQ','easy',1,
  'In a Pushdown Automaton, acceptance by empty stack and acceptance by final state are:',
  'Equivalent in power, defining the same language family',
  'Different, final state is more powerful',
  'Different, empty stack is more powerful',
  'Only used in deterministic mode',
  'A',
  '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> A PDA accepting by empty stack can be converted to one accepting by final state, and vice versa. They define the same class of Context-Free Languages.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('pda');

-- Q20 — CFG Left Recursion (medium)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,option_a,option_b,option_c,option_d,correct_option,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='toc'),
  (SELECT id FROM chapters WHERE slug='context-free-languages' LIMIT 1),
  (SELECT id FROM topics WHERE slug='cfg-ambiguity' LIMIT 1),
  'gate-cse',false,NULL,'MCQ','medium',2,
  'Eliminating direct left recursion from $A \rightarrow A\alpha \mid \beta$ yields:',
  '$A \rightarrow \beta A''$, $A'' \rightarrow \alpha A'' \mid \epsilon$',
  '$A \rightarrow \alpha A''$, $A'' \rightarrow \beta A'' \mid \epsilon$',
  '$A \rightarrow A''\beta$, $A'' \rightarrow A''\alpha \mid \epsilon$',
  '$A \rightarrow \beta A$, $A \rightarrow \alpha A \mid \epsilon$',
  'A',
  '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> The standard algorithm replaces the left-recursive loop $A \rightarrow A \alpha$ with right-recursive rules using a new variable $A''$.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('cfg');

-- Q21 — Pumping Lemma CFL bound (medium)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,option_a,option_b,option_c,option_d,correct_option,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='toc'),
  (SELECT id FROM chapters WHERE slug='context-free-languages' LIMIT 1),
  (SELECT id FROM topics WHERE slug='cfl-pumping' LIMIT 1),
  'gate-cse',false,NULL,'MCQ','medium',2,
  'In the Pumping Lemma for Context-Free Languages ($w = uvxyz$), which rule forces the pumped segments to be close together?',
  '$|vxy| \le p$',
  '$|vy| > 0$',
  '$|uxy| \le p$',
  '$|v| = |y|$',
  'A',
  '<p><strong>✓ Answer: A — $|vxy| \le p$.</strong></p><p><strong>Rationale:</strong> The constraint $|vxy| \le p$ restricts the bounding distance in the parse tree, ensuring the repeating subtrees representing $v$ and $y$ are localized.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('pumping-lemma');

-- Q22 — Decidability of CFL bounds (medium)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,option_a,option_b,option_c,option_d,correct_option,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='toc'),
  (SELECT id FROM chapters WHERE slug='context-free-languages' LIMIT 1),
  (SELECT id FROM topics WHERE slug='cfl-closure' LIMIT 1),
  'gate-cse',false,NULL,'MCQ','medium',2,
  'Which operation for Context-Free Grammars is explicitly Undecidable?',
  'Testing Emptiness ($L(G) = \emptyset$)',
  'Testing Membership ($w \in L(G)$)',
  'Testing Equivalence ($L(G_1) = L(G_2)$)',
  'Testing Finiteness (Is $L(G)$ finite?)',
  'C',
  '<p><strong>✓ Answer: C.</strong></p><p><strong>Rationale:</strong> The "Equivalence Problem" comparing whether two CFGs generate the same language is undecidable. Emptiness, Membership, and Finiteness are all decidable.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('decidability','cfg');

-- Q23 — Linear Bounded Automata (medium)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,option_a,option_b,option_c,option_d,correct_option,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='toc'),
  (SELECT id FROM chapters WHERE slug='turing-machines' LIMIT 1),
  (SELECT id FROM topics WHERE slug='chomsky-hierarchy' LIMIT 1),
  'gate-cse',false,NULL,'MCQ','medium',2,
  'Linear Bounded Automata (LBA) uniquely accept languages categorized under which Chomsky classification?',
  'Type-0 (Recursively Enumerable)',
  'Type-1 (Context-Sensitive)',
  'Type-2 (Context-Free)',
  'Type-3 (Regular)',
  'B',
  '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> The Chomsky Hierarchy maps Linear Bounded Automata directly to Context-Sensitive Languages (Type-1).</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('hierarchy','turing-machine');

-- Q24 — Rice's Theorem Implementation (hard)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,option_a,option_b,option_c,option_d,correct_option,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='toc'),
  (SELECT id FROM chapters WHERE slug='decidability' LIMIT 1),
  (SELECT id FROM topics WHERE slug='rices-theorem-topic' LIMIT 1),
  'gate-cse',false,NULL,'MCQ','hard',2,
  'Rice''s Theorem states that for Turing Machines:',
  'Any non-trivial property of the language recognized is Undecidable',
  'Every semantic property is Decidable',
  'Only trivial properties are Undecidable',
  'Syntax checking is Undecidable',
  'A',
  '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> Rice''s Theorem definitively proves that any non-trivial semantic property of Recursively Enumerable languages is mathematically undecidable.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('rices-theorem','decidability');

-- Q25 — Recursive Enumerable properties (medium)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,option_a,option_b,option_c,option_d,correct_option,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='toc'),
  (SELECT id FROM chapters WHERE slug='turing-machines' LIMIT 1),
  (SELECT id FROM topics WHERE slug='recursive-languages' LIMIT 1),
  'gate-cse',false,NULL,'MCQ','medium',2,
  'If language $L$ and its complement $\overline{L}$ are both Recursively Enumerable, what must be true about $L$?',
  'It is Context-Free',
  'It is strictly Regular',
  'It is Recursive (Decidable)',
  'It is Undecidable',
  'C',
  '<p><strong>✓ Answer: C.</strong></p><p><strong>Rationale:</strong> Post''s Theorem guarantees that if both $L$ and $\overline{L}$ are Recursively Enumerable (Turing Recognizable), then $L$ is Recursive (Turing Decidable).</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('decidability');

-- Q26 — CFG grammar generation bounds (easy)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,option_a,option_b,option_c,option_d,correct_option,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='toc'),
  (SELECT id FROM chapters WHERE slug='context-free-languages' LIMIT 1),
  (SELECT id FROM topics WHERE slug='cfg-ambiguity' LIMIT 1),
  'gate-cse',false,NULL,'MCQ','easy',1,
  'What characterizes the production rules of Context-Free Grammars?',
  'The left-hand side must consist of exactly one non-terminal variable',
  'Both sides must have equal length',
  'The right-hand side can only contain terminals',
  'The rules must generate regular expressions',
  'A',
  '<p><strong>✓ Answer: A.</strong></p><p><strong>Rationale:</strong> The lack of context constraint defining CFGs requires that only a single non-terminal variable exists on the left side of any production.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('cfg');

-- Q27 — Pushdown Automata Non-Determinism (medium)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,option_a,option_b,option_c,option_d,correct_option,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='toc'),
  (SELECT id FROM chapters WHERE slug='context-free-languages' LIMIT 1),
  (SELECT id FROM topics WHERE slug='pda-basics' LIMIT 1),
  'gate-cse',false,NULL,'MCQ','medium',2,
  'Are Deterministic Pushdown Automata (DPDA) functionally equivalent in computational power to Non-Deterministic Pushdown Automata (NPDA)?',
  'Yes, they accept the exact same language class',
  'No, NPDA accepting power strictly exceeds DPDA',
  'No, DPDA accepting power strictly exceeds NPDA',
  'Yes, provided the stack alphabet is binary',
  'B',
  '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> NPDAs accept all Context-Free Languages. DPDAs accept only Deterministic Context-Free Languages (a strict subset). Therefore, NPDA is strictly more powerful.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('pda','cfg');

-- Q28 — The Halting Problem (easy)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,option_a,option_b,option_c,option_d,correct_option,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='toc'),
  (SELECT id FROM chapters WHERE slug='decidability' LIMIT 1),
  (SELECT id FROM topics WHERE slug='halting-problem' LIMIT 1),
  'gate-cse',false,NULL,'MCQ','easy',1,
  'The Halting Problem determines whether an arbitrary Turing Machine halts on a given input. What is its decidability status?',
  'Decidable',
  'Undecidable, but Recursively Enumerable',
  'Not Recursively Enumerable',
  'Context-Free',
  'B',
  '<p><strong>✓ Answer: B.</strong></p><p><strong>Rationale:</strong> The Halting Problem is recognized by a Universal Turing Machine (so it is RE), but we cannot determine when it will loop infinitely, making it Undecidable.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('decidability','halting-problem');

-- Part 3 complete.
