-- ═══════════════════════════════════════════════════════════════════════════
-- EXAMFORGE — CD PYQ SEED v2 (Part 5 / 8)
-- NAT Questions Q46–Q55 (Parsing tables, counts, expressions)
-- ═══════════════════════════════════════════════════════════════════════════

-- Q46 — Left factoring count (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,nat_answer_min,nat_answer_max,nat_unit,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='syntax-analysis' LIMIT 1), (SELECT id FROM topics WHERE slug='grammar-modifications' LIMIT 1), 'gate-cse',false,NULL,'NAT','easy',1, 'Consider grammar rule $A \rightarrow abBc \mid abBd \mid abBe$. Upon applying left factoring to eliminate the common prefix, exactly how many new non-terminal variables are introduced?', 1.00,1.00,NULL, '<p><strong>✓ Answer: 1.</strong></p><p><strong>Rationale:</strong> The prefix $abB$ factors out, transforming into $A \rightarrow abB A''$ and $A'' \rightarrow c \mid d \mid e$. one new variable ($A''$) is introduced.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('parsing');

-- Q47 — Syntax Tree Nodes (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,nat_answer_min,nat_answer_max,nat_unit,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='ast' LIMIT 1), 'gate-cse',false,NULL,'NAT','medium',2, 'Evaluate the expression $(a + b) \times (c - d) + e$. How many total nodes (internal + leaves) exist in the optimal Abstract Syntax Tree (AST)?', 9.00,9.00,NULL, '<p><strong>✓ Answer: 9.</strong></p><p><strong>Rationale:</strong> The AST stores 5 operand leaves ($a, b, c, d, e$) and 4 operator internal nodes ($+, \times, -, +$). Total nodes = 9.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('ast');

-- Q48 — DAG Node Compression (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,nat_answer_min,nat_answer_max,nat_unit,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='dag-topic' LIMIT 1), 'gate-cse',false,NULL,'NAT','medium',2, 'Given the code block $X = A + B; Y = A + B; Z = X \times Y$, what is the total number of nodes required to construct the Directed Acyclic Graph (DAG)?', 4.00,4.00,NULL, '<p><strong>✓ Answer: 4.</strong></p><p><strong>Rationale:</strong> The DAG maps $A$ and $B$ (2 leaves). It computes $A+B$ as one node shared by both $X$ and $Y$. It maps the $\times$ operator combining the shared node with itself. Total nodes = 4.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('dag');

-- Q49 — LR(0) Items (hard)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,nat_answer_min,nat_answer_max,nat_unit,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='syntax-analysis' LIMIT 1), (SELECT id FROM topics WHERE slug='lr0-slr1' LIMIT 1), 'gate-cse',false,NULL,'NAT','hard',2, 'A grammar contains exactly 3 production rules. Rule 1 has right-side length 2. Rule 2 has length 1. Rule 3 has length 0 (epsilon). Counting the augmented production, what is the maximum number of distinct LR(0) items generated?', 8.00,8.00,NULL, '<p><strong>✓ Answer: 8.</strong></p><p><strong>Rationale:</strong> Number of items equals rule length + 1. Augmented rule: 2 items. Rule 1 ($len 2$): 3 items. Rule 2 ($len 1$): 2 items. Rule 3 ($len 0$): 1 item ($A \rightarrow .$). Total = $2 + 3 + 2 + 1 = 8$.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('lr-parsing');

-- Q50 — Lexical Token Count (easy)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,nat_answer_min,nat_answer_max,nat_unit,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='lexical-analysis' LIMIT 1), (SELECT id FROM topics WHERE slug='token-identification' LIMIT 1), 'gate-cse',false,NULL,'NAT','easy',1, 'Count the exact number of lexical tokens in this C statement: `int arr[10] = {1, 2, 3};` (Assume no trailing EOF token is required)', 14.00,14.00,NULL, '<p><strong>✓ Answer: 14.</strong></p><p><strong>Rationale:</strong> The tokens are: `int`, `arr`, `[`, `10`, `]`, `=`, `{`, `1`, `,`, `2`, `,`, `3`, `}`, `;`. The count is exactly 14.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('lexical-analysis','tokens');

-- Q51 — Basic Blocks Count (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,nat_answer_min,nat_answer_max,nat_unit,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='optimization-runtime' LIMIT 1), (SELECT id FROM topics WHERE slug='basic-blocks' LIMIT 1), 'gate-cse',false,NULL,'NAT','medium',2, 'A segment of TAC has lines 1-10. Jump statements are identified at lines 4 (goto 8) and 9 (goto 2). How many basic blocks are logically partitioned in this code map?', 4.00,4.00,NULL, '<p><strong>✓ Answer: 4.</strong></p><p><strong>Rationale:</strong> The leaders (starts) are line 1 (first), line 8 (target), line 2 (target), line 5 (follows jump), and line 10 (follows jump). The blocks span 1-1, 2-4, 5-7, 8-9, and 10.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('optimization');

-- Q52 — First Set Size (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,nat_answer_min,nat_answer_max,nat_unit,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='syntax-analysis' LIMIT 1), (SELECT id FROM topics WHERE slug='first-follow-sets' LIMIT 1), 'gate-cse',false,NULL,'NAT','medium',2, 'Grammar: $S \rightarrow aB \mid \epsilon$, $B \rightarrow c \mid dS$. What is the cardinality (number of elements) in $FIRST(S)$?', 2.00,2.00,NULL, '<p><strong>✓ Answer: 2.</strong></p><p><strong>Rationale:</strong> $FIRST(S)$ receives ''$a$'' from $aB$, and receives $\epsilon$ directly. So $FIRST(S) = \{a, \epsilon\}$. Cardinality is 2.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('first-follow');

-- Q53 — LALR vs CLR states (hard)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,nat_answer_min,nat_answer_max,nat_unit,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='syntax-analysis' LIMIT 1), (SELECT id FROM topics WHERE slug='lalr-clr' LIMIT 1), 'gate-cse',false,NULL,'NAT','hard',2, 'If an LR(0) parser constructing a specific grammar generates exactly 20 states, what is the exact number of states the resulting LALR(1) parser generates?', 20.00,20.00,NULL, '<p><strong>✓ Answer: 20.</strong></p><p><strong>Rationale:</strong> LALR(1) parsers have the same number of states as the LR(0) and SLR(1) core parsers. Only the lookahead are merged. The state count matches perfectly.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('lr-parsing');

-- Q54 — Minimum Temporaries (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,nat_answer_min,nat_answer_max,nat_unit,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='sdt-icg' LIMIT 1), (SELECT id FROM topics WHERE slug='tac' LIMIT 1), 'gate-cse',false,NULL,'NAT','medium',2, 'Converting the logic $X = (A + B) * (C - D)$ into standard 3-Address Code mandates temporary outputs. What is the minimum number of independent temporary variables required assuming standard $t_1, t_2...$ assignments without optimizer reuse?', 2.00,2.00,NULL, '<p><strong>✓ Answer: 2.</strong></p><p><strong>Rationale:</strong> Step 1: $t_1 = A + B$. Step 2: $t_2 = C - D$. Step 3: $X = t_1 * t_2$. Exactly 2 intermediate temporaries are produced.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('icg');

-- Q55 — Follow Set computation (medium)
WITH q AS (INSERT INTO questions (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,question_text,nat_answer_min,nat_answer_max,nat_unit,explanation) VALUES ((SELECT id FROM subjects WHERE slug='cd'), (SELECT id FROM chapters WHERE slug='syntax-analysis' LIMIT 1), (SELECT id FROM topics WHERE slug='first-follow-sets' LIMIT 1), 'gate-cse',false,NULL,'NAT','medium',2, 'Grammar: $S \rightarrow AB$, $A \rightarrow a \mid \epsilon$, $B \rightarrow b$. Assume $S$ is the start variable. How many elements exist in $FOLLOW(A)$?', 1.00,1.00,NULL, '<p><strong>✓ Answer: 1.</strong></p><p><strong>Rationale:</strong> $FOLLOW(A)$ equals $FIRST(B)$, minus $\epsilon$. Since $B \rightarrow b$, $FIRST(B) = \{b\}$. Thus, $FOLLOW(A)$ contains the element $\{b\}$.</p>') RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('first-follow');

-- Part 5 complete.
