-- ═══════════════════════════════════════════════════════════════════════════
-- EXAMFORGE — DM PYQ SEED v2  (Part 5 / 8)
-- NAT Questions Q46–Q55 (Logic, Combinatorics, Graphs)
-- ═══════════════════════════════════════════════════════════════════════════

-- Q46 — Combinatorics: Derangements (NAT, medium)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,nat_answer_min,nat_answer_max,nat_unit,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='dm'),
  (SELECT id FROM chapters WHERE slug='combinatorics' LIMIT 1),
  (SELECT id FROM topics WHERE slug='permutations-combinations' LIMIT 1),
  'gate-cse',false,NULL,'NAT','medium',2,
  '5 friends place their hats in a pile. What is the total number of ways (derangements) that NO friend receives their own original hat?',
  44.00,44.00,NULL,
  '<p><strong>✓ Answer: 44.</strong></p><p><strong>Step-by-step:</strong><br>Using the derangement formula $D_n = n! \sum_{i=0}^n \frac{(-1)^i}{i!}$.<br>For $n = 5$:<br>$D_5 = 120 \left(\frac{1}{1} - \frac{1}{1} + \frac{1}{2} - \frac{1}{6} + \frac{1}{24} - \frac{1}{120}\right)$<br>$D_5 = 120 \left(0 + \frac{60 - 20 + 5 - 1}{120}\right)$<br>$D_5 = 44$.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('combinatorics');

-- Q47 — Graph Theory: Chromatic Number Planar (NAT, easy)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,nat_answer_min,nat_answer_max,nat_unit,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='dm'),
  (SELECT id FROM chapters WHERE slug='graph-theory' LIMIT 1),
  (SELECT id FROM topics WHERE slug='graph-coloring' LIMIT 1),
  'gate-cse',false,NULL,'NAT','easy',1,
  'According to the famous map-coloring theorem, what is the maximum chromatic number required to color ANY planar graph?',
  4.00,4.00,NULL,
  '<p><strong>✓ Answer: 4.</strong></p><p><strong>Rationale:</strong> The Four Color Theorem guarantees that the vertices of any planar graph can be colored with at most 4 colors such that no two adjacent vertices share the exact same color.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('graphs','matching');

-- Q48 — Logic: Valid Truth Assignments (NAT, medium)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,nat_answer_min,nat_answer_max,nat_unit,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='dm'),
  (SELECT id FROM chapters WHERE slug='logic-proofs' LIMIT 1),
  (SELECT id FROM topics WHERE slug='propositional-logic' LIMIT 1),
  'gate-cse',false,NULL,'NAT','medium',2,
  'Consider the boolean expression $E = p \rightarrow (q \lor r)$. For exactly how many of the 8 possible truth assignments to $p, q, r$ is $E$ false?',
  1.00,1.00,NULL,
  '<p><strong>✓ Answer: 1.</strong></p><p><strong>Step-by-step:</strong><br>An implication $X \rightarrow Y$ is false IF AND ONLY IF $X$ is True and $Y$ is False.<br>Here, $X$ is $p$. So $p$ must be True.<br>$Y$ is $(q \lor r)$. For $Y$ to be False, both $q$ and $r$ must be False.<br>This yields exactly one row in the truth table: $p=T, q=F, r=F$.<br>For all other 7 assignments, the expression evaluates to True.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('logic');

-- Q49 — Set Theory: Count Subsets (NAT, easy)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,nat_answer_min,nat_answer_max,nat_unit,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='dm'),
  (SELECT id FROM chapters WHERE slug='sets-relations-functions' LIMIT 1),
  (SELECT id FROM topics WHERE slug='set-theory' LIMIT 1),
  'gate-cse',false,NULL,'NAT','easy',1,
  'If set $A$ contains exactly 5 elements, what is the exact number of proper subsets of $A$?',
  31.00,31.00,NULL,
  '<p><strong>✓ Answer: 31.</strong></p><p><strong>Step-by-step:</strong><br>- Total possible subsets generated by the power set is $2^n$. For $n=5$, $2^5 = 32$.<br>- Proper subsets exclude the set itself (which is improper).<br>- Therefore, number of proper subsets = $32 - 1 = 31$.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('sets');

-- Q50 — Combinatorics: Handshakes (NAT, easy)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,nat_answer_min,nat_answer_max,nat_unit,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='dm'),
  (SELECT id FROM chapters WHERE slug='combinatorics' LIMIT 1),
  (SELECT id FROM topics WHERE slug='permutations-combinations' LIMIT 1),
  'gate-cse',false,NULL,'NAT','easy',1,
  'If there are exactly 12 people at a party and every person shakes hands with every other person exactly once, what is the total number of handshakes?',
  66.00,66.00,NULL,
  '<p><strong>✓ Answer: 66.</strong></p><p><strong>Step-by-step:</strong><br>This is choosing 2 people out of 12 for each handshake. Order does not matter.<br>$\binom{12}{2} = \frac{12 \times 11}{2} = 66$.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('combinatorics');

-- Q51 — Graph Theory: Total Degrees (NAT, easy)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,nat_answer_min,nat_answer_max,nat_unit,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='dm'),
  (SELECT id FROM chapters WHERE slug='graph-theory' LIMIT 1),
  (SELECT id FROM topics WHERE slug='graph-basics' LIMIT 1),
  'gate-cse',false,NULL,'NAT','easy',1,
  'A simple undirected graph possesses exactly 14 edges. What is the sum of the degrees of all its vertices?',
  28.00,28.00,NULL,
  '<p><strong>✓ Answer: 28.</strong></p><p><strong>Step-by-step:</strong><br>By the Handshaking Lemma, the sum of degrees $\sum deg(v) = 2 \times E$.<br>Edges $E = 14$.<br>Sum $= 2 \times 14 = 28$.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('graphs');

-- Q52 — Trees: Nodes from Edges (NAT, medium)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,nat_answer_min,nat_answer_max,nat_unit,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='dm'),
  (SELECT id FROM chapters WHERE slug='graph-theory' LIMIT 1),
  (SELECT id FROM topics WHERE slug='trees-properties' LIMIT 1),
  'gate-cse',false,NULL,'NAT','medium',2,
  'An undirected tree graph is known to contain exactly 15 edges. How many vertices does it contain?',
  16.00,16.00,NULL,
  '<p><strong>✓ Answer: 16.</strong></p><p><strong>Step-by-step:</strong><br>A fundamental property of any tree is that it is a connected acyclic graph. A tree containing $n$ vertices always contains $n - 1$ edges.<br>$E = V - 1$<br>$15 = V - 1 \implies V = 16$.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('trees','graphs');

-- Q53 — Combinatorics: Integer Partitions (NAT, hard)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,nat_answer_min,nat_answer_max,nat_unit,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='dm'),
  (SELECT id FROM chapters WHERE slug='combinatorics' LIMIT 1),
  (SELECT id FROM topics WHERE slug='inclusion-exclusion' LIMIT 1),
  'gate-cse',false,NULL,'NAT','hard',2,
  'Find the total number of integers from 1 to 100 that are divisible by either 3 or 5, but not by both.',
  47.00,47.00,NULL,
  '<p><strong>✓ Answer: 47.</strong></p><p><strong>Step-by-step:</strong><br>Let $A$ = divisible by 3, $B$ = divisible by 5. We want $|A| + |B| - 2|A \cap B|$ (symmetric difference).<br>$|A| = \lfloor 100/3 \rfloor = 33$<br>$|B| = \lfloor 100/5 \rfloor = 20$<br>$|A \cap B|$ (divisible by 15) $= \lfloor 100/15 \rfloor = 6$<br>Symmetric difference = $33 + 20 - 2(6) = 53 - 12 = 47$.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('combinatorics');

-- Q54 — Partial Orders: Number of pairs (NAT, medium)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,nat_answer_min,nat_answer_max,nat_unit,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='dm'),
  (SELECT id FROM chapters WHERE slug='sets-relations-functions' LIMIT 1),
  (SELECT id FROM topics WHERE slug='relations-properties' LIMIT 1),
  'gate-cse',false,NULL,'NAT','medium',2,
  'Consider the set $A = \{1, 2, 3\}$. The relation "less than or equal to" ($\le$) is defined on this set. How many ordered pairs populate this relation?',
  6.00,6.00,NULL,
  '<p><strong>✓ Answer: 6.</strong></p><p><strong>Step-by-step:</strong><br>The relation is $R = \{(x, y) \mid x \le y\}$.<br>Evaluating for $A$:<br>For $x=1$: (1,1), (1,2), (1,3)<br>For $x=2$: (2,2), (2,3)<br>For $x=3$: (3,3)<br>Total number of pairs = $3 + 2 + 1 = 6$.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('relations','sets');

-- Q55 — Recurrence Evaluation (NAT, easy)
WITH q AS (INSERT INTO questions
  (subject_id,chapter_id,topic_id,exam_slug,is_pyq,gate_year,type,difficulty,marks,
   question_text,nat_answer_min,nat_answer_max,nat_unit,explanation)
VALUES(
  (SELECT id FROM subjects WHERE slug='dm'),
  (SELECT id FROM chapters WHERE slug='combinatorics' LIMIT 1),
  (SELECT id FROM topics WHERE slug='recurrence-relations' LIMIT 1),
  'gate-cse',false,NULL,'NAT','easy',1,
  'Given $a_n = 2a_{n-1} + 3$ with base case $a_0 = 1$. What is the integer value of $a_3$?',
  29.00,29.00,NULL,
  '<p><strong>✓ Answer: 29.</strong></p><p><strong>Step-by-step:</strong><br>Calculate iteratively from base case:<br>$a_0 = 1$<br>$a_1 = 2(1) + 3 = 5$<br>$a_2 = 2(5) + 3 = 13$<br>$a_3 = 2(13) + 3 = 26 + 3 = 29$.</p>'
) RETURNING id)
INSERT INTO question_tags (question_id,tag_id) SELECT q.id,t.id FROM q,tags t WHERE t.slug IN ('recurrence','combinatorics');

-- Part 5 complete.
